### PR TITLE
Update

### PR DESCRIPTION
**Pull request by bbhtt**
723d18305872ac1c9f99f19a53959cc36ea1a843 fixes some indentation issues like https://github.com/flathub/com.github.ojubaorg.Othman/blob/4b508d6bcd66fc1ea3e65843bf606a166cf60acf/com.github.ojubaorg.Othman.json#L79 and doesn't contain any changes other than that. Please see the next two commits for the actual updates.

Ping @muayyad-alsadi, please review when you have the chance. Thanks!

### CODE REVIEW

**Comment by bbhtt** [comment]
> Started [test build 103330](https://buildbot.flathub.org/#/builders/32/builds/103330)

It's stuck on commiting builds :/

**Comment by bbhtt** [comment]
bot, build

**Comment by muayyad-alsadi** [comment]
font is not working

Screenshot from 2022-08-04 00-07-55

**Comment by bbhtt** [comment]
> font is not working

That's weird, it seems to be working fine for me?

Screenshot

**Comment by muayyad-alsadi** [comment]
Maybe you have the font on the host

**Comment by bbhtt** [comment]
> Maybe you have the font on the host

No I don't have any regional language specific fonts installed on host, in fact the only fonts that are reporting Arabic support on my system are the GNU Free fonts:

```
$ fc-list :lang=ar

/usr/share/fonts/gnu-free/FreeSerif.otf
/usr/share/fonts/gnu-free/FreeMono.otf
/usr/share/fonts/gnu-free/FreeSerifBold.otf
```

If I run this inside the sandbox of the app:

```
$ flatpak run --command=sh com.github.ojubaorg.Othman

[📦 com.github.ojubaorg.Othman ~]$ fc-list :lang=ar

/app/share/fonts/Amiri-Bold.ttf: Amiri:style=Bold
/usr/share/fonts/dejavu/DejaVuSansCondensed-Bold.ttf
/usr/share/fonts/dejavu/DejaVuSansMono.ttf
/run/host/fonts/gnu-free/FreeSerif.otf
/usr/share/fonts/dejavu/DejaVuSansMono-Bold.ttf
/app/share/fonts/AmiriQuran.ttf: Amiri Quran
/usr/share/fonts/dejavu/DejaVuSans.ttf
/app/share/fonts/Amiri-Slanted.ttf
/app/share/fonts/AmiriQuranColored.ttf
/usr/share/fonts/gnu-free/FreeSerifBold.ttf
/usr/share/fonts/dejavu/DejaVuSans-Bold.ttf
/run/host/fonts/gnu-free/FreeSerifBold.otf
/app/share/fonts/Amiri-Regular.ttf: Amiri:style=Regular
/usr/share/fonts/gnu-free/FreeSerif.ttf
/app/share/fonts/Amiri-BoldSlanted.ttf
/usr/share/fonts/dejavu/DejaVuSansCondensed.ttf
/run/host/fonts/gnu-free/FreeMono.otf
/usr/share/fonts/gnu-free/FreeMono.ttf
```
And the Amiri font comes up:

```
[📦 com.github.ojubaorg.Othman ~]$ fc-match -s serif|grep Amiri
Amiri-Regular.ttf: "Amiri" "Regular"
[📦 com.github.ojubaorg.Othman ~]$ fc-match -s serif:lang=ar|grep Amiri
Amiri-Regular.ttf: "Amiri" "Regular"
````

**Comment by muayyad-alsadi** [comment]
most likely the problem is from my side.

**Pull request merged**
