### PR TITLE
Update runtime and patch othman to work

### LINKED ISSUE #1: Needs a 128x128px icon
For some reason, this isn't getting a 128x128px icon on the [apps page](https://beta.flathub.org/apps), which is strange, since there's one in the upstream source.

### PR DESCRIPTION
**Pull request by lionirdeadman**
Patch sent upstream : https://github.com/ojuba-org/othman/pull/29

Also fix #1

### CODE REVIEW

**Comment by muayyad-alsadi** [comment]
Build failed

**Comment by lionirdeadman** [comment]
Yes, it failed because of #1, I've made a simple patch for it now.

**Comment by lionirdeadman** [comment]
Small mistake in my patching, I forgot to make it install. Fixed now. :sweat_smile:

**Comment by lionirdeadman** [comment]
Turns out that convert can't do 128px icons to 128px icons so it wouldn't work. I've now fixed that. Now it should all work.

**Pull request merged**
